basics:
  email: anakin@skywalker.com
  location:
    city: Mos Eisley
    countryCode: Tatooine
  name: Anakin Skywalker
  phone: 123-456-7890
  profiles:
  - network: Github
    url: https://github.com/alexlren
    username: alexlren
  - network: Linkedin
    url: https://www.linkedin.com/anakin
    username: anakin
  url: https://shaoner.com
education:
- area: Jedi / General
  institution: Jedi Academy
  startDate: '2011-01-01'
meta:
  breaks_before:
    education: true
projects:
- description: a multiplatform gameboy engine
  keywords:
  - Rust
  - React.js
  name: padme
  url: https://padme.cc
- description: A special lightsaber
  keywords:
  - C++
  - Qt
  name: lightsaber
skills:
- keywords:
  - Rust
  - Python
  name: Languages
- keywords:
  - numpy
  - Qt
  name: Frameworks/libraries
- keywords:
  - AWS
  - docker
  - kubernetes
  name: Devops
- keywords:
  - emacs
  - Makefile
  name: Tools
- keywords:
  - Linux
  - FreeBSD
  name: OS
work:
- highlights:
  - Killed a few rebels here and there
  - Tracked Jedi all around the galaxy
  - Practiced the force with my master Darth Sidious
  - Killed some younglings
  name: Empire
  position: Darth Vader
  startDate: '2016-08-01'
- endDate: '2016-01-01'
  highlights:
  - Learn the force with my master Obiwan Kenobi
  - Helped the clones during the Clone wars
  - Freed the princess of Naboo
  - Killed the Count Dooku
  name: Jedi Academy
  position: Jedi / General
  startDate: '2011-01-01'
